site_name: GemX Analyzer
site_description: Gateway + orquestrador com BYOK, SSE sólido e governança
site_author: Kubex Ecosystem
site_url: https://kubex-ecosystem.github.io/analyzer/

repo_name: kubex-ecosystem/analyzer
repo_url: https://github.com/kubex-ecosystem/analyzer
edit_uri: edit/main/docs/

docs_dir: ../../docs

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  favicon: assets/kubex_gemx_analyzer_banner.png
  logo: assets/kubex_gemx_analyzer_banner.png

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: kubex-ecosystem
      repo: analyzer
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - Concepts: getting-started/concepts.md
  - Architecture:
      - Overview: architecture/overview.md
      - Components: architecture/components.md
      - Data & Persistence: architecture/data-persistence.md
      - Flows (Analyzer ⇄ Grompt ⇄ LookAtni ⇄ GoBE): architecture/flows.md
  - API & CLI:
      - HTTP API: reference/http.md
      - CLI (analyzer): cli/commands.md
      - Recipes: cli/recipes.md
  - Providers & BYOK:
      - Overview: providers/byok.md
      - OpenAI (Go Gateway): providers/openai-go-gateway.md
      - Gemini: providers/gemini.md
      - Anthropic: providers/anthropic.md
      - Groq: providers/groq.md
  - Backend Gateway:
      - Config (YAML): backend/config.md
      - Auth & Tenancy: backend/auth-tenancy.md
      - Resilience (Rate/Circuit/Retry): backend/resilience.md
      - Observability: backend/observability.md
  - Guides:
      - First Analyzer Cycle (end-to-end): guides/e2e-cycle.md
      - Lookatni + Analyzer (repo integration): guides/lookatni-integration.md
      - Contextual Code Chat: guides/contextual-chat.md
  - Operations:
      - Security & BYOK: operations/security.md
      - Troubleshooting: operations/troubleshooting.md
      - Release/Build: operations/release.md
  - About:
      - Contributing: about/contributing.md
      - Changelog: about/changelog.md
      - License: about/license.md
