providers:
  openai:
    type: openai
    base_url: https://api.openai.com
    key_env: OPENAI_API_KEY
    default_model: gpt-4o-mini

  gemini:
    type: gemini
    base_url: https://generativelanguage.googleapis.com
    key_env: GEMINI_API_KEY
    default_model: gemini-2.5-flash

  # Future providers (uncomment when implemented)
  # anthropic:
  #   type: anthropic
  #   base_url: https://api.anthropic.com
  #   key_env: ANTHROPIC_API_KEY
  #   default_model: claude-3-5-sonnet-latest  # groq:
  #   type: groq
  #   base_url: https://api.groq.com
  #   key_env: GROQ_API_KEY
  #   default_model: llama-3.1-70b-versatile

  # openrouter:
  #   type: openrouter
  #   base_url: https://openrouter.ai/api
  #   key_env: OPENROUTER_API_KEY
  #   default_model: google/gemini-flash-1.5

  # ollama:
  #   type: ollama
  #   base_url: http://localhost:11434
  #   key_env: ""
  #   default_model: llama3.1
